# Generated by Django 5.2.4 on 2025-07-30 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='district',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.city', verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='estate',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='estate',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.city', verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='estate',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.district', verbose_name='Район'),
        ),
        migrations.AddField(
            model_name='estate',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_ads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='estate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='product.estate'),
        ),
        migrations.AddField(
            model_name='image',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.estate'),
        ),
    ]
