# Generated by Django 5.2.4 on 2025-08-01 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_favorite_feedback_feedbackresponse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbackresponse',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='feedbackresponse',
            name='user',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='FeedbackResponse',
        ),
    ]
